version: '3'

services:
    api:
        env_file:
            "./api/api.env"
        build:
            context: ./api
            dockerfile: ./Dockerfile
        ports:
            - "5000:5000"
    client:
        build:
            context: ./client
            dockerfile: ./Dockerfile
        ports:
            - "3000:3000"
        links:
            - "api"